"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.services = void 0;
const sample_1 = require("./sample/sample");
const twilio_1 = require("./twilio/twilio");
const driver_1 = require("./driver/driver");
const transaction_1 = require("./transaction/transaction");
const wallet_1 = require("./wallet/wallet");
const shop_1 = require("./shop/shop");
const product_1 = require("./product/product");
const modifier_option_1 = require("./modifier_option/modifier_option");
const modifier_1 = require("./modifier/modifier");
const product_category_1 = require("./product_category/product_category");
const order_1 = require("./order/order");
const lineitem_1 = require("./lineitem/lineitem");
const business_1 = require("./business/business");
const employee_role_1 = require("./employee_role/employee_role");
const user_1 = require("./user/user");
const services = (app) => {
    app.configure(sample_1.sample);
    app.configure(twilio_1.twilio);
    app.configure(driver_1.driver);
    app.configure(transaction_1.transaction);
    app.configure(wallet_1.wallet);
    app.configure(shop_1.shop);
    app.configure(product_1.product);
    app.configure(modifier_1.modifier);
    app.configure(modifier_option_1.modifierOption);
    app.configure(product_category_1.productCategory);
    app.configure(order_1.order);
    app.configure(lineitem_1.lineitem);
    app.configure(business_1.business);
    app.configure(employee_role_1.employeeRole);
    app.configure(user_1.user);
    // All services will be registered here
};
exports.services = services;
